apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.webphotobook.myapp
    namespace: myapp
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - MySQL
      name: nv.mysql.myapp-egress-0
      ports: tcp/3306
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: mysql.myapp
        - key: domain
          op: =
          value: myapp
        name: nv.mysql.myapp
        original_name: ""
    - action: allow
      applications:
      - DNS
      name: nv.rke2-coredns-rke2-coredns.kube-system-egress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: kube-system
        - key: service
          op: =
          value: rke2-coredns-rke2-coredns.kube-system
        name: nv.rke2-coredns-rke2-coredns.kube-system
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.webphotobook.myapp-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: kube-system
        - key: service
          op: =
          value: rke2-ingress-nginx-controller.kube-system
        name: nv.rke2-ingress-nginx-controller.kube-system
        original_name: ""
    - action: allow
      applications:
      - HTTP
      name: nv.webphotobook.myapp-ingress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: external
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: ls
      path: /usr/bin/ls
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: ping
      path: /usr/bin/ping
    - action: allow
      allow_update: false
      name: python3
      path: /usr/bin/python3.11
    - action: allow
      allow_update: false
      name: sh
      path: /usr/bin/bash
    process_profile:
      baseline: zero-drift
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: myapp
        - key: service
          op: =
          value: webphotobook.myapp
        name: nv.webphotobook.myapp
        original_name: ""
kind: List
metadata: null
